# Generated by Django 5.0.6 on 2024-06-01 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_color_name_alter_products_size_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='color_name',
            new_name='color_variant',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='size_name',
            new_name='size_variant',
        ),
    ]
